name: MISP2 tests
on: [pull_request]
jobs:
  run-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run test
        run: ./gradlew test
      - name: Store upload test artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Test results
          path: |
            /home/runner/work/misp2/misp2/web-app/build/reports/tests/test/index.html
            /home/runner/work/misp2/misp2/web-app/build/it-screenshots/
